import { useMemo, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, Brain, BriefcaseBusiness, Check, ChevronRight, Cross, GraduationCap, HeartPulse, Menu, Search, Shield, Sparkles, Target, Timer, X } from 'lucide-react';

type Exam = { id:string; title:string; full:string; category:string; questions:string; icon:any; accent:string; description:string; tags:string[] };

const exams:Exam[]=[
{id:'pmp',title:'PMP',full:'Project Management Professional',category:'Project Management',questions:'2,000+',icon:BriefcaseBusiness,accent:'violet',description:'Master scenario-based decision making across people, process, and business environments.',tags:['Scenario-based','Mock exams','Analytics']},
{id:'nclex',title:'NCLEX-RN',full:'National Council Licensure Examination',category:'Healthcare',questions:'3,000+',icon:HeartPulse,accent:'cyan',description:'Clinical judgment practice with high-quality rationales and Next Generation case studies.',tags:['NGN cases','Clinical judgment','Rationales']},
{id:'sergeant',title:'Police Sergeant',full:'Promotional Examination Prep',category:'Law Enforcement',questions:'500+',icon:Shield,accent:'amber',description:'Focused promotional exam preparation built around leadership, law, supervision, and operations.',tags:['USA Core','Leadership','Source-based']},
{id:'step1',title:'USMLE Step 1',full:'United States Medical Licensing Examination',category:'Medical',questions:'Coming soon',icon:Cross,accent:'rose',description:'Integrated foundational science and clinical reasoning for medical board preparation.',tags:['Clinical reasoning','Foundations','Coming soon']}
];

function App(){
 const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const [selected,setSelected]=useState<Exam|null>(null);
 const filtered=useMemo(()=>exams.filter(e=>(e.title+e.full+e.category).toLowerCase().includes(query.toLowerCase())),[query]);
 const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <div className="app">
  <nav><button className="brand" onClick={()=>scroll('home')}><span className="brandmark"><GraduationCap size={22}/></span><b>ASCEND</b><span>PREP</span></button><div className="navlinks"><button onClick={()=>scroll('exams')}>Exam Library</button><button onClick={()=>scroll('features')}>How it works</button><button onClick={()=>scroll('pricing')}>Pricing</button></div><div className="navactions"><button className="signin">Sign in</button><button className="primary small" onClick={()=>scroll('exams')}>Start practicing <ArrowRight size={15}/></button></div><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
  {menu&&<div className="mobilemenu"><button onClick={()=>{scroll('exams');setMenu(false)}}>Exam Library</button><button onClick={()=>{scroll('features');setMenu(false)}}>How it works</button><button onClick={()=>{scroll('pricing');setMenu(false)}}>Pricing</button><button>Sign in</button></div>}

  <main id="home">
   <section className="hero"><div className="glow one"/><div className="glow two"/><div className="heroCopy"><div className="eyebrow"><Sparkles size={14}/> One platform. Career-defining exams.</div><h1>Prepare with purpose.<br/><span>Perform with confidence.</span></h1><p>Premium question banks, realistic mock exams, and actionable performance analytics for the certifications that move your career forward.</p><div className="heroActions"><button className="primary" onClick={()=>scroll('exams')}>Find your exam <ArrowRight size={17}/></button><button className="ghost" onClick={()=>scroll('features')}>Explore the platform</button></div><div className="trust"><span><Check/>Focused practice</span><span><Check/>Detailed explanations</span><span><Check/>Progress analytics</span></div></div>
   <div className="heroVisual"><div className="dashboard"><div className="dashTop"><div><small>YOUR READINESS</small><strong>Keep building momentum.</strong></div><span className="live">● ACTIVE</span></div><div className="scoreRow"><div className="ring"><span>82<small>%</small></span></div><div className="scoreText"><b>Exam readiness</b><span>+7% this week</span><div className="progress"><i/></div></div></div><div className="stats"><div><Target/><b>78%</b><small>Accuracy</small></div><div><BookOpen/><b>428</b><small>Questions</small></div><div><Timer/><b>41h</b><small>Study time</small></div></div><div className="miniCard"><span className="miniIcon"><Brain/></span><div><small>RECOMMENDED NEXT</small><b>Adaptive Practice · 20 questions</b></div><ChevronRight/></div></div><div className="floatCard"><BarChart3/><span><small>WEEKLY GROWTH</small><b>+12.4%</b></span></div></div></section>

   <section className="examSection" id="exams"><div className="sectionHead"><div><span className="kicker">EXAM LIBRARY</span><h2>Choose what you're preparing for.</h2><p>Each exam is a dedicated learning experience, powered by the same focused practice engine.</p></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search exams..."/></label></div><div className="examGrid">{filtered.map(e=><ExamCard key={e.id} exam={e} onClick={()=>setSelected(e)}/>)}</div></section>

   <section className="features" id="features"><div className="featureIntro"><span className="kicker">BUILT FOR MASTERY</span><h2>More than a question bank.</h2><p>Practice deliberately. Understand every decision. Know exactly where to focus next.</p></div><div className="featureGrid"><Feature icon={Brain} n="01" title="Learn through explanations" text="Understand why the correct answer works and why each alternative falls short."/><Feature icon={Target} n="02" title="Practice what matters" text="Create focused sessions by topic, difficulty, status, or performance."/><Feature icon={BarChart3} n="03" title="See your weak points" text="Turn every session into clear performance signals and targeted next steps."/><Feature icon={Timer} n="04" title="Simulate exam day" text="Build endurance and decision speed with realistic timed mock examinations."/></div></section>

   <section className="pricing" id="pricing"><div><span className="kicker">SIMPLE ACCESS</span><h2>Study for one exam.<br/>Or unlock the platform.</h2><p>Start with the certification you need today. Expand your access whenever your goals change.</p></div><div className="priceCards"><div className="price"><small>SINGLE EXAM</small><h3>Focused Access</h3><p>Everything you need for one selected exam.</p><ul><li><Check/>Full question bank</li><li><Check/>Mock exams</li><li><Check/>Performance analytics</li><li><Check/>Detailed explanations</li></ul><button onClick={()=>scroll('exams')}>Choose an exam <ArrowRight/></button></div><div className="price featured"><span className="popular">BEST VALUE</span><small>ALL ACCESS</small><h3>Ascend Complete</h3><p>One membership for every available exam.</p><ul><li><Check/>All exam libraries</li><li><Check/>All mock exams</li><li><Check/>Unified analytics</li><li><Check/>Future exam additions</li></ul><button className="primary">Explore All Access <ArrowRight/></button></div></div></section>
  </main>
  <footer><div className="brand"><span className="brandmark"><GraduationCap size={20}/></span><b>ASCEND</b><span>PREP</span></div><p>Professional exam preparation, built around deliberate practice.</p><span>© 2026 Ascend Prep</span></footer>
  {selected&&<ExamModal exam={selected} close={()=>setSelected(null)}/>} 
 </div>
}

function ExamCard({exam,onClick}:{exam:Exam,onClick:()=>void}){const Icon=exam.icon;return <button className={'examCard '+exam.accent} onClick={onClick}><div className="cardTop"><span className="examIcon"><Icon/></span><span className="count">{exam.questions} QUESTIONS</span></div><small>{exam.category.toUpperCase()}</small><h3>{exam.title}</h3><h4>{exam.full}</h4><p>{exam.description}</p><div className="tags">{exam.tags.map(t=><span key={t}>{t}</span>)}</div><div className="cardCta">Explore exam <ArrowRight size={17}/></div></button>}
function Feature({icon:Icon,n,title,text}:any){return <div className="featureCard"><span className="num">{n}</span><span className="featureIcon"><Icon/></span><h3>{title}</h3><p>{text}</p></div>}
function ExamModal({exam,close}:{exam:Exam,close:()=>void}){const Icon=exam.icon;return <div className="modalBack" onMouseDown={close}><div className={'modal '+exam.accent} onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="examIcon large"><Icon/></span><small>{exam.category.toUpperCase()}</small><h2>{exam.title}</h2><h4>{exam.full}</h4><p>{exam.description}</p><div className="modalStats"><div><b>{exam.questions}</b><span>Questions</span></div><div><b>4</b><span>Practice modes</span></div><div><b>24/7</b><span>Access</span></div></div><button className="primary wide">Start {exam.title} preparation <ArrowRight/></button><button className="outline wide" onClick={close}>Back to exam library</button></div></div>}
export default App;